CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    price NUMERIC(14, 2) NOT NULL CHECK (price >= 0),
    category_id BIGINT NOT NULL REFERENCES categories(id),
    image_url TEXT NOT NULL DEFAULT '',
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    views BIGINT NOT NULL DEFAULT 0,
    cart_adds BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS product_sizes (
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    size TEXT NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    PRIMARY KEY (product_id, size)
);

CREATE TABLE IF NOT EXISTS integrations (
    provider TEXT PRIMARY KEY,
    kind TEXT NOT NULL CHECK (kind IN ('payment', 'delivery')),
    enabled BOOLEAN NOT NULL DEFAULT false,
    public_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    secret_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY,
    status TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    total NUMERIC(14, 2) NOT NULL CHECK (total >= 0),
    payment_provider TEXT REFERENCES integrations(provider),
    idempotency_key TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_items (
    order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    size TEXT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(14, 2) NOT NULL CHECK (unit_price >= 0),
    PRIMARY KEY (order_id, product_id, size)
);

CREATE TABLE IF NOT EXISTS deliveries (
    order_id UUID PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
    provider TEXT NOT NULL REFERENCES integrations(provider),
    external_id TEXT,
    status TEXT NOT NULL,
    address JSONB NOT NULL,
    tracking_number TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor TEXT NOT NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS products_category_idx ON products(category_id);
CREATE INDEX IF NOT EXISTS products_created_at_idx ON products(created_at DESC);
CREATE INDEX IF NOT EXISTS orders_status_created_idx ON orders(status, created_at DESC);
CREATE INDEX IF NOT EXISTS audit_log_entity_idx ON audit_log(entity_type, entity_id);

INSERT INTO categories(name, slug) VALUES
    ('Одежда', 'clothing'), ('Обувь', 'shoes'), ('Аксессуары', 'accessories')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO products(name, description, price, category_id, stock)
SELECT seed.name, seed.description, seed.price, categories.id, seed.stock
FROM (VALUES
    ('Aurora Hoodie', 'Плотный хлопок, свободный силуэт', 7490.00, 'Одежда', 24),
    ('Orbit Sneakers', 'Лёгкие городские кроссовки', 11990.00, 'Обувь', 12),
    ('Mono Pack', 'Минималистичный рюкзак', 5290.00, 'Аксессуары', 31)
) AS seed(name, description, price, category, stock)
JOIN categories ON categories.name = seed.category
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO product_sizes(product_id, size)
SELECT products.id, sizes.size
FROM products
JOIN (VALUES
    ('Aurora Hoodie', 'S'), ('Aurora Hoodie', 'M'), ('Aurora Hoodie', 'L'), ('Aurora Hoodie', 'XL'),
    ('Orbit Sneakers', '39'), ('Orbit Sneakers', '40'), ('Orbit Sneakers', '41'),
    ('Orbit Sneakers', '42'), ('Orbit Sneakers', '43')
) AS sizes(product_name, size) ON sizes.product_name = products.name
ON CONFLICT DO NOTHING;