from typing import Protocol

from store.domain import Integration, Product


class StoreRepository(Protocol):
    def list_products(self, include_inactive: bool = False) -> list[Product]: ...
    def get_product(self, product_id: int) -> Product | None: ...
    def save_product(self, product: Product) -> Product: ...
    def delete_product(self, product_id: int) -> bool: ...
    def list_categories(self) -> list[dict[str, object]]: ...
    def save_category(self, name: str) -> dict[str, object]: ...
    def delete_category(self, category_id: int) -> bool: ...
    def increment(self, product_id: int, metric: str) -> None: ...
    def list_integrations(self) -> list[Integration]: ...
    def save_integration(self, integration: Integration) -> None: ...


class CaptchaVerifier(Protocol):
    def verify(self, token: str, ip: str) -> bool: ...
