from typing import Protocol

from store.domain import Integration, Product


class StoreRepository(Protocol):
    def list_products(self, include_inactive: bool = False) -> list[Product]: ...
    def get_product(self, product_id: int) -> Product | None: ...
    def save_product(self, product: Product) -> Product: ...
    def delete_product(self, product_id: int) -> bool: ...
    def list_categories(self) -> list[dict[str, object]]: ...
    def save_category(self, name: str) -> dict[str, object]: ...
    def delete_category(self, category_id: int) -> bool: ...
    def increment(self, product_id: int, metric: str) -> None: ...
    def list_integrations(self) -> list[Integration]: ...
    def save_integration(self, integration: Integration) -> None: ...
    def delete_integration(self, provider: str) -> bool: ...
    def get_integration_config(self, provider: str, enabled_only: bool = True) -> dict[str, object] | None: ...
    def create_order(self, order: dict[str, object], items: list[dict[str, object]]) -> dict[str, object]: ...
    def set_order_payment(self, order_id: str, payment_id: str, status: str) -> None: ...
    def update_order_by_payment(self, payment_id: str, status: str) -> bool: ...
    def get_order(self, order_id: str) -> dict[str, object] | None: ...


class CaptchaVerifier(Protocol):
    def verify(self, token: str, ip: str) -> bool: ...
